Fix workspace patch (#56)
* Follow upstream istio-proxy changes

Signed-off-by: Taiki Ono <taiki@tetrate.io>

* Ignore .bazelversion

Signed-off-by: Taiki Ono <taiki@tetrate.io>

* Use "Exception" to raise

Python error:

  TypeError: exceptions must derive from BaseException

Signed-off-by: Taiki Ono <taiki@tetrate.io>

* Revert "Follow upstream istio-proxy changes"

This reverts commit e44164a78af060694dd42000a8a340459fc1550f.

Signed-off-by: Taiki Ono <taiki@tetrate.io>

* New patch to follow upstream changes

Signed-off-by: Taiki Ono <taiki@tetrate.io>

* Apply patches correctly

Example output will be:

  applying patch: workspace_patches/istio-proxy/0001-WORKSPACE.patch
  patching file WORKSPACE
  applying patch: workspace_patches/istio-proxy/0000-WORKSPACE.patch
  patching file WORKSPACE

Signed-off-by: Taiki Ono <taiki@tetrate.io>

* Replace outdated function use

Example output on errors:

  subprocess.CalledProcessError: Command '['patch', '-p1', 'WORKSPACE', 'workspace_patches/istio-proxy/0001-WORKSPACE.patch']' returned non-zero exit status 1

Signed-off-by: Taiki Ono <taiki@tetrate.io>

* Correct logic

Signed-off-by: Taiki Ono <taiki@tetrate.io>

* Replace outdated functions

Signed-off-by: Taiki Ono <taiki@tetrate.io>

* Fix CI

Signed-off-by: Taiki Ono <taiki@tetrate.io>